use std::{path::PathBuf, sync::Arc};

use serde::Serialize;

use crate::{
    engine::manager::asset::{AssetRegistry, AssetSlot},
    model::{Audio, Kind, Stored},
};

#[derive(Copy, Clone, Default, Eq, PartialEq, Ord, PartialOrd, Hash, Debug)]
#[repr(transparent)]
/// An identifier for an `AudioAsset`
pub struct AudioAssetID(slotmap::KeyData);

impl From<slotmap::KeyData> for AudioAssetID {
    fn from(key_data: slotmap::KeyData) -> Self {
        Self(key_data)
    }
}

// SAFETY: This impl was generated by the expanded `slotmap::new_key_type` macro
unsafe impl slotmap::Key for AudioAssetID {
    fn data(&self) -> slotmap::KeyData {
        self.0
    }
}
slotmap::__serialize_key!(AudioAssetID);
slotmap::new_key_type!();

/// Trait defining an `Asset` of a certain `Kind`.
pub trait Asset<K: Kind> {}

#[derive(Debug)]
/// Defines the loading state of an `Asset`.
pub enum AssetData<Data: Clone> {
    /// The `Asset` is being loaded.
    Pending,
    /// The `Asset` has been loaded and the `Data` is ready to consume.
    Ready(Data),

    /// The `Asset` has failed to load correctly, with this [`Error`](anyhow::Error)
    Failed(anyhow::Error),
}

#[derive(Debug, Clone, Serialize)]
/// An `Asset` for `Audio` data
pub struct AudioAsset {
    #[serde(skip)]
    /// The actual audio payload
    pub payload: AudioAssetPayload,
    /// Inherent gain
    pub gain: f32,
    /// The sample rate of this [`AudioAsset`]. Should match the [`sample_rate()`](crate::engine::Engine::sample_rate) of the parent [`Engine`](crate::engine::Engine)
    pub sample_rate: u32,
    pub channels: u16,
    pub path: PathBuf,
    pub len: usize,
}

#[derive(Debug, Clone)]
/// The form of the audio payload for an `AudioAsset`.
pub enum AudioAssetPayload {
    /// In-memory interleaved audio data
    ResidentInterleaved(Arc<[f32]>),
    /// Interleaved audio data streamed from disk
    StreamingInterleaved,
}

impl Stored for AudioAsset {
    type ID = AudioAssetID;
    type Location = AssetRegistry;
    type Storage = AssetSlot<Audio>;

    fn access(loc: &Self::Location) -> &slotmap::SlotMap<Self::ID, Self::Storage> {
        &loc.audio
    }

    fn access_mut(loc: &mut Self::Location) -> &mut slotmap::SlotMap<Self::ID, Self::Storage> {
        &mut loc.audio
    }
}

impl Asset<Audio> for AudioAsset {}
