[package]
name = "libautark"
version = "0.1.0"
edition = "2024"
readme = "../README.md"
keywords = ["audio", "music", "daw", "dsp"]
categories = ["multimedia::audio"]

[lints]
workspace = true

[dependencies]
anyhow = {workspace = true}
arc-swap = "1.9.2"
assert_no_alloc = "1.1.2"
async-trait = "0.1.91"
audio-blocks = "0.7.0"
audioadapter-buffers = "4.0.0"
console-subscriber = {workspace = true}
cpal = "0.18.1"
dyn-clone = "1.0.20"
flume = "0.12.0"
futures = "0.3.33"
rtrb = "0.3.4"
rubato = "4.0.0"
serde = {workspace = true}
slotmap = {version = "1.1.1", features = ["serde"]}
symphonia = {version = "0.6.0", features = ["mp3"]}
thiserror = {workspace = true}
tokio = { workspace = true }

