[package]
name = "autark"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.103"
vizia = {git = "https://github.com/vizia/vizia"}
libautark = { path = "../libautark" }
rmp-serde = "1.3.1"
serde = "1.0.228"
thiserror = "2.0.18"
rtrb = "0.3.4"
tokio = {version = "1.53.1", features = ["full"]}
